### ISSUE TITLE
cprox v2

### ISSUE THREAD

**Issue by NobleMajo** [majo418/cprox#1]

**Comment by MarcoKrooss** [comment]
v2

**Comment by NobleMajo** [comment]
There will be a security update in the future.
Maybe at some point also an auto lets encrypt settings _(flag+env var)_ because I already have this local implemented and tested, but no version 2.
If anything, I add a new rule type and don't make any breaking changes to the current version.

It's not that the current system is perfect, but rather that CProX should remain a lightweight and easily configurable web server.
Unfortunately, in a v2 brainstorming I went beyond this _(lightweight and easily configurable)_ within the first 2 minutes.

This server is more for development purposes or smaller quick deployments and tests. For systems with higher load, you should take the time to overcome the entry hurdle of a decent web server _(example: nginx, apache2, httpd)_ or go straight to kubernetes _(+cert-manager, +nginx-ingress)_ setup.
