### ISSUE TITLE
How to configure a proxy load balancer?

### ISSUE THREAD

**Issue by jakobkroenun** [majo418/cprox#3]
is it possible or how to configure a proxy load balancer?
I mean a reverse proxy targeting multiple destination addresses.

When I ask the cprox server, I want to reach one server on the first request and a different server address and port on the second time through the proxy.

Example:
1. 127.0.0.1:58080
2. 127.0.0.1:58081
3. 192.168.0.40:58080

**Comment by NobleMajo** [comment]
> is it possible or how to configure a proxy load balancer? I mean a reverse proxy targeting multiple destination addresses.
> 
> When I ask the cprox server, I want to reach one server on the first request and a different server address and port on the second time through the proxy.
> 
> Example:
> 
> 1. 127.0.0.1:58080
> 2. 127.0.0.1:58081
> 3. 192.168.0.40:58080

Yes @jakobkroenun !

Try this rule for ur example:
```sh
cprox *=PROXY:http://127.0.0.1:58080,http://127.0.0.1:58081,http://192.168.0.40:58080
```
